#!/usr/bin/env bash
set -euo pipefail

echo "--- :remix: Remix Build (Production)"
echo ""
echo "NODE_ENV: $NODE_ENV"
echo ""

echo "Building Remix app for production..."
sleep 1
echo ""
echo "Building server..."
echo "  route:root"
echo "  route:routes/_index"
echo "  route:routes/about"
echo "  route:routes/blog.\$slug"
echo "  route:routes/api.users"
echo "  route:routes/dashboard"
echo "  route:routes/dashboard.settings"
sleep 2
echo ""
echo "✓ server built (build/index.js)"
echo ""
echo "Building browser..."
echo "  route:root"
echo "  route:routes/_index"
echo "  route:routes/about"
echo "  route:routes/blog.\$slug"
echo "  route:routes/api.users"
echo "  route:routes/dashboard"
echo "  route:routes/dashboard.settings"
sleep 2
echo ""
echo "✓ browser built (public/build)"
echo ""
echo "Built in 3.7s"

echo ""
echo "--- :test_tube: npm run test"
echo ""
echo "> remix-app@1.0.0 test"
echo "> vitest run"
echo ""
echo " ✓ app/routes/_index.test.tsx (3 tests) 124ms"
echo "   ✓ renders homepage hero"
echo "   ✓ displays call-to-action button"
echo "   ✓ navigates to signup on CTA click"
echo ""
echo " ✓ app/routes/dashboard.test.tsx (4 tests) 89ms"
echo "   ✓ requires authentication"
echo "   ✓ displays user dashboard"
echo "   ✓ loads user data from loader"
echo "   ✓ handles error boundary"
echo ""
echo " ✓ app/utils/session.test.ts (5 tests) 43ms"
echo "   ✓ creates session cookie"
echo "   ✓ parses session cookie"
echo "   ✓ validates session token"
echo "   ✓ handles expired sessions"
echo "   ✓ destroys session correctly"
echo ""
sleep 1
echo " Test Files  3 passed (3)"
echo "      Tests  12 passed (12)"
echo "   Start at  $(date '+%H:%M:%S')"
echo "   Duration  2.18s"

echo ""
echo "+++ :white_check_mark: Remix production build completed"
